#!/usr/bin/python
import re

ParsedOutputFilename = 'Nexus5Parse.csv'
SourceFilename = 'nexus5Dump.txt'

def FileWrite(string):
    WriteFile = open(ParsedOutputFilename, 'a')
    for i in range(len(string)):
        WriteFile.write('%s,' %(string[i]))
    WriteFile.write('\n')
    WriteFile.close()

def FindPattern(line):
    match = re.search(r'[\d.]+.[\d.]\s[\d.]+.[\d.]\s[\d.]+.[\d.]\s',line)
    if match:
        FileWrite(match.group().split()[0:])
        print match.group().split()[0:]

def main():
    file = open(SourceFilename,'r')
    for line in file:
        FindPattern(line)
    file.close()
    lineCount = 0
    file = open(ParsedOutputFilename,'r')
    for lines in file:
        lineCount += 1
    file.close()
    print lineCount


if __name__ == '__main__':
  main()
